export const HINT_ICONS = {
  charge:        { label: 'Charge',    color: '#5b8dd9' },
  jump:          { label: 'Jump',      color: '#7a9fd4' },
  flight:        { label: 'Flight',    color: '#9ab5e0' },
  teleport:      { label: 'Blink',     color: '#6fa8dc' },
  chase:         { label: 'Chase',     color: '#7b9ed4' },
  tears_aimed:   { label: 'Aimed',     color: '#e07b54' },
  tears_burst:   { label: 'Burst',     color: '#d95f2b' },
  tears_ring:    { label: 'Ring',      color: '#c94a1a' },
  bounce:        { label: 'Bounce',    color: '#e09b54' },
  homing:        { label: 'Homing',    color: '#d97b3a' },
  spectral:      { label: 'Spectral',  color: '#e0b05a' },
  laser:         { label: 'Beam',      color: '#ff4444' },
  explosive:     { label: 'Explode',   color: '#e05a20' },
  stomp:         { label: 'Stomp',     color: '#8b6914' },
  spawns_creep:  { label: 'Creep',     color: '#5a7a3a' },
  floor_hazard:  { label: 'Hazard',    color: '#6b7a2a' },
  multi_phase:   { label: '2+ Phases', color: '#9b5dd9' },
  splits:        { label: 'Splits',    color: '#b07dd4' },
  invincible:    { label: 'Shield',    color: '#7b4db0' },
  orbit:         { label: 'Orbit',     color: '#c09be0' },
  summons:       { label: 'Summons',   color: '#d48bd9' },
  swipe:         { label: 'Swipe',     color: '#a06090' },
  effect:        { label: 'Effect',    color: '#d060b0' },
};
